// AUTO-GENERATED oleh scripts/gen-aspect-data.mjs — jangan edit manual.
// Sumber: public/data/position_competency_standards.csv + public/data/participant_aspect_scores.csv
// Regenerate: node scripts/gen-aspect-data.mjs (atau npm run seed, sudah dihook di sana).

export const ASPECTS = [
  "Orientasi Hasil",
  "Kerjasama",
  "Komunikasi",
  "Daya Analisis",
  "Adaptabilitas",
  "Inisiatif",
  "Pelayanan Pelanggan",
  "Integritas",
  "Pengembangan Diri",
  "Pengambilan Keputusan",
  "Manajemen Waktu",
  "Disiplin",
  "Keterampilan Interpersonal"
] as const;
export type Aspect = (typeof ASPECTS)[number];

/** Standar tiap aspek (skala 1-5) per judul posisi. */
export const POSITION_STANDARDS: Record<string, Record<Aspect, number>> = {
  "Head of Engineering": {
    "Orientasi Hasil": 4,
    "Kerjasama": 5,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 5,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 5,
    "Integritas": 4,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 4
  },
  "Senior Engineer": {
    "Orientasi Hasil": 4,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "Frontend Lead": {
    "Orientasi Hasil": 4,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 4,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "Backend Lead": {
    "Orientasi Hasil": 4,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Chief Executive Officer": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "Chief Strategy Officer": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 4,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 4,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "VP Corporate Strategy": {
    "Orientasi Hasil": 4,
    "Kerjasama": 4,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 4,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 5
  },
  "Head of Governance": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Head of Finance": {
    "Orientasi Hasil": 4,
    "Kerjasama": 5,
    "Komunikasi": 4,
    "Daya Analisis": 5,
    "Adaptabilitas": 4,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 4,
    "Integritas": 4,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 5
  },
  "Senior Finance Analyst": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 4,
    "Adaptabilitas": 2,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Finance Analyst": {
    "Orientasi Hasil": 2,
    "Kerjasama": 2,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 2,
    "Disiplin": 1,
    "Keterampilan Interpersonal": 2
  },
  "Controller": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "HR Business Partner": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 4,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  },
  "HR Manager": {
    "Orientasi Hasil": 4,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 2,
    "Adaptabilitas": 4,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Talent Acquisition Lead": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 2
  },
  "People Ops Specialist": {
    "Orientasi Hasil": 3,
    "Kerjasama": 1,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 2,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 3,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  },
  "VP Operations": {
    "Orientasi Hasil": 4,
    "Kerjasama": 4,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 4,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 4,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "Operations Manager": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 2,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Supply Chain Lead": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 4,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "Operations Analyst": {
    "Orientasi Hasil": 3,
    "Kerjasama": 1,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 2,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 2,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 2
  },
  "Head of Marketing": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 4,
    "Daya Analisis": 5,
    "Adaptabilitas": 3,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 4,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 4
  },
  "Senior Marketing Manager": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Brand Manager": {
    "Orientasi Hasil": 4,
    "Kerjasama": 2,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Growth Marketing Lead": {
    "Orientasi Hasil": 3,
    "Kerjasama": 2,
    "Komunikasi": 3,
    "Daya Analisis": 2,
    "Adaptabilitas": 3,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "Senior Brand Strategist": {
    "Orientasi Hasil": 3,
    "Kerjasama": 4,
    "Komunikasi": 4,
    "Daya Analisis": 2,
    "Adaptabilitas": 3,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Chief Revenue Officer": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "Creative Director": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "Principal Engineer": {
    "Orientasi Hasil": 4,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 4
  },
  "Operations Strategist": {
    "Orientasi Hasil": 2,
    "Kerjasama": 2,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "Growth Marketing Manager": {
    "Orientasi Hasil": 4,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 4,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 4,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  },
  "Senior Finance Manager": {
    "Orientasi Hasil": 2,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "Supply Chain Manager": {
    "Orientasi Hasil": 3,
    "Kerjasama": 2,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "Digital Content Specialist": {
    "Orientasi Hasil": 2,
    "Kerjasama": 2,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 1,
    "Integritas": 3,
    "Pengembangan Diri": 1,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 2,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  }
};

/** Skor tiap aspek (skala 1-5) per id partisipan. */
export const PARTICIPANT_ASPECT_SCORES: Record<string, Record<Aspect, number>> = {
  "p01": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "p02": {
    "Orientasi Hasil": 1,
    "Kerjasama": 2,
    "Komunikasi": 1,
    "Daya Analisis": 2,
    "Adaptabilitas": 1,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 1,
    "Integritas": 1,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 2,
    "Disiplin": 1,
    "Keterampilan Interpersonal": 2
  },
  "p03": {
    "Orientasi Hasil": 4,
    "Kerjasama": 2,
    "Komunikasi": 4,
    "Daya Analisis": 2,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 2
  },
  "p04": {
    "Orientasi Hasil": 4,
    "Kerjasama": 2,
    "Komunikasi": 2,
    "Daya Analisis": 4,
    "Adaptabilitas": 2,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 2,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 2,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "p05": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "p06": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 4,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "p07": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "p08": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 4,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 5,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "p09": {
    "Orientasi Hasil": 4,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 4,
    "Adaptabilitas": 3,
    "Inisiatif": 3,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "p10": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 2,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 2
  },
  "p11": {
    "Orientasi Hasil": 1,
    "Kerjasama": 1,
    "Komunikasi": 1,
    "Daya Analisis": 1,
    "Adaptabilitas": 1,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 1,
    "Integritas": 1,
    "Pengembangan Diri": 1,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 1,
    "Disiplin": 1,
    "Keterampilan Interpersonal": 1
  },
  "p12": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 4,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 4,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 5,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 5
  },
  "p13": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 2,
    "Adaptabilitas": 3,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 2,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 4
  },
  "p14": {
    "Orientasi Hasil": 2,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 3
  },
  "p15": {
    "Orientasi Hasil": 1,
    "Kerjasama": 2,
    "Komunikasi": 1,
    "Daya Analisis": 1,
    "Adaptabilitas": 1,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 2,
    "Integritas": 1,
    "Pengembangan Diri": 1,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 1,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 1
  },
  "p16": {
    "Orientasi Hasil": 2,
    "Kerjasama": 1,
    "Komunikasi": 2,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 1,
    "Integritas": 2,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 2,
    "Disiplin": 1,
    "Keterampilan Interpersonal": 1
  },
  "p17": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 5,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "p18": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 4,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 2,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 2
  },
  "p19": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 2,
    "Daya Analisis": 4,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 2,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 2
  },
  "p20": {
    "Orientasi Hasil": 2,
    "Kerjasama": 2,
    "Komunikasi": 1,
    "Daya Analisis": 3,
    "Adaptabilitas": 1,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 1,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 2
  },
  "p21": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 4,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 5
  },
  "p22": {
    "Orientasi Hasil": 1,
    "Kerjasama": 2,
    "Komunikasi": 1,
    "Daya Analisis": 1,
    "Adaptabilitas": 2,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 2,
    "Integritas": 2,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 1,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 1
  },
  "p23": {
    "Orientasi Hasil": 4,
    "Kerjasama": 2,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 3,
    "Integritas": 2,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 2,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 2
  },
  "p24": {
    "Orientasi Hasil": 1,
    "Kerjasama": 1,
    "Komunikasi": 2,
    "Daya Analisis": 1,
    "Adaptabilitas": 2,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 2,
    "Integritas": 2,
    "Pengembangan Diri": 1,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 2,
    "Disiplin": 1,
    "Keterampilan Interpersonal": 2
  },
  "p25": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 5,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 5
  },
  "p26": {
    "Orientasi Hasil": 5,
    "Kerjasama": 4,
    "Komunikasi": 4,
    "Daya Analisis": 4,
    "Adaptabilitas": 4,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 5,
    "Integritas": 5,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 5,
    "Manajemen Waktu": 5,
    "Disiplin": 4,
    "Keterampilan Interpersonal": 4
  },
  "p27": {
    "Orientasi Hasil": 4,
    "Kerjasama": 4,
    "Komunikasi": 3,
    "Daya Analisis": 2,
    "Adaptabilitas": 4,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 3,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 3,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 4
  },
  "p28": {
    "Orientasi Hasil": 3,
    "Kerjasama": 3,
    "Komunikasi": 4,
    "Daya Analisis": 2,
    "Adaptabilitas": 4,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 3,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 3,
    "Manajemen Waktu": 4,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 4
  },
  "p29": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 2,
    "Daya Analisis": 2,
    "Adaptabilitas": 2,
    "Inisiatif": 4,
    "Pelayanan Pelanggan": 4,
    "Integritas": 4,
    "Pengembangan Diri": 3,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 2,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  },
  "p30": {
    "Orientasi Hasil": 2,
    "Kerjasama": 3,
    "Komunikasi": 3,
    "Daya Analisis": 3,
    "Adaptabilitas": 2,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 2,
    "Integritas": 3,
    "Pengembangan Diri": 4,
    "Pengambilan Keputusan": 2,
    "Manajemen Waktu": 3,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  },
  "p31": {
    "Orientasi Hasil": 5,
    "Kerjasama": 5,
    "Komunikasi": 5,
    "Daya Analisis": 4,
    "Adaptabilitas": 5,
    "Inisiatif": 5,
    "Pelayanan Pelanggan": 4,
    "Integritas": 5,
    "Pengembangan Diri": 5,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 5,
    "Disiplin": 5,
    "Keterampilan Interpersonal": 4
  },
  "p32": {
    "Orientasi Hasil": 2,
    "Kerjasama": 2,
    "Komunikasi": 4,
    "Daya Analisis": 3,
    "Adaptabilitas": 3,
    "Inisiatif": 2,
    "Pelayanan Pelanggan": 3,
    "Integritas": 2,
    "Pengembangan Diri": 2,
    "Pengambilan Keputusan": 4,
    "Manajemen Waktu": 3,
    "Disiplin": 3,
    "Keterampilan Interpersonal": 3
  },
  "p33": {
    "Orientasi Hasil": 3,
    "Kerjasama": 2,
    "Komunikasi": 2,
    "Daya Analisis": 3,
    "Adaptabilitas": 1,
    "Inisiatif": 1,
    "Pelayanan Pelanggan": 3,
    "Integritas": 2,
    "Pengembangan Diri": 1,
    "Pengambilan Keputusan": 1,
    "Manajemen Waktu": 2,
    "Disiplin": 2,
    "Keterampilan Interpersonal": 3
  }
};
