// AUTO-GENERATED by scripts/seed.mjs — do not edit by hand.
// Source of record: public/data/participants.csv + assignments.csv. Regenerate: npm run seed
import type { CanonicalData } from "./types";

export const CANONICAL: CanonicalData = {
  "positions": [
    {
      "id": "pos-p01",
      "title": "Head of Engineering",
      "department": "Teknologi"
    },
    {
      "id": "pos-p02",
      "title": "Senior Engineer",
      "department": "Teknologi"
    },
    {
      "id": "pos-p03",
      "title": "Frontend Lead",
      "department": "Teknologi"
    },
    {
      "id": "pos-p04",
      "title": "Backend Lead",
      "department": "Teknologi"
    },
    {
      "id": "pos-p05",
      "title": "Chief Executive Officer",
      "department": "Strategi"
    },
    {
      "id": "pos-p06",
      "title": "Chief Strategy Officer",
      "department": "Strategi"
    },
    {
      "id": "pos-p07",
      "title": "VP Corporate Strategy",
      "department": "Strategi"
    },
    {
      "id": "pos-p08",
      "title": "Head of Governance",
      "department": "Strategi"
    },
    {
      "id": "pos-p09",
      "title": "Head of Finance",
      "department": "Keuangan"
    },
    {
      "id": "pos-p10",
      "title": "Senior Finance Analyst",
      "department": "Keuangan"
    },
    {
      "id": "pos-p11",
      "title": "Finance Analyst",
      "department": "Keuangan"
    },
    {
      "id": "pos-p12",
      "title": "Controller",
      "department": "Keuangan"
    },
    {
      "id": "pos-p13",
      "title": "HR Business Partner",
      "department": "SDM"
    },
    {
      "id": "pos-p14",
      "title": "HR Manager",
      "department": "SDM"
    },
    {
      "id": "pos-p15",
      "title": "Talent Acquisition Lead",
      "department": "SDM"
    },
    {
      "id": "pos-p16",
      "title": "People Ops Specialist",
      "department": "SDM"
    },
    {
      "id": "pos-p17",
      "title": "VP Operations",
      "department": "Operasional"
    },
    {
      "id": "pos-p18",
      "title": "Operations Manager",
      "department": "Operasional"
    },
    {
      "id": "pos-p19",
      "title": "Supply Chain Lead",
      "department": "Operasional"
    },
    {
      "id": "pos-p20",
      "title": "Operations Analyst",
      "department": "Operasional"
    },
    {
      "id": "pos-p21",
      "title": "Head of Marketing",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p22",
      "title": "Senior Marketing Manager",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p23",
      "title": "Brand Manager",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p24",
      "title": "Growth Marketing Lead",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p25",
      "title": "Senior Brand Strategist",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p26",
      "title": "Chief Revenue Officer",
      "department": "Strategi"
    },
    {
      "id": "pos-p27",
      "title": "Creative Director",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p28",
      "title": "Principal Engineer",
      "department": "Teknologi"
    },
    {
      "id": "pos-p29",
      "title": "Operations Strategist",
      "department": "Operasional"
    },
    {
      "id": "pos-p30",
      "title": "Growth Marketing Manager",
      "department": "Pemasaran"
    },
    {
      "id": "pos-p31",
      "title": "Senior Finance Manager",
      "department": "Keuangan"
    },
    {
      "id": "pos-p32",
      "title": "Supply Chain Manager",
      "department": "Operasional"
    },
    {
      "id": "pos-p33",
      "title": "Digital Content Specialist",
      "department": "Pemasaran"
    }
  ],
  "teams": [
    {
      "id": "ENG",
      "name": "Engineering Team",
      "type": "FUNCTIONAL",
      "leaderId": "p01",
      "reportToId": "p05"
    },
    {
      "id": "EXE",
      "name": "Executive Office Team",
      "type": "FUNCTIONAL",
      "leaderId": "p05",
      "reportToId": null
    },
    {
      "id": "FIN",
      "name": "Finance Team",
      "type": "FUNCTIONAL",
      "leaderId": "p09",
      "reportToId": "p05"
    },
    {
      "id": "HR",
      "name": "Human Resources Team",
      "type": "FUNCTIONAL",
      "leaderId": "p13",
      "reportToId": "p05"
    },
    {
      "id": "OPS",
      "name": "Operations Team",
      "type": "STRUCTURAL",
      "leaderId": "p17",
      "reportToId": "p05"
    },
    {
      "id": "SNM",
      "name": "Sales & Marketing Team",
      "type": "FUNCTIONAL",
      "leaderId": "p21",
      "reportToId": "p05"
    }
  ],
  "participants": [
    {
      "id": "p01",
      "name": "Jude Bellingham",
      "positionId": "pos-p01",
      "teamId": "ENG",
      "managerId": "p05",
      "successorForId": null,
      "disc": "D",
      "potential": "high",
      "photoUrl": null
    },
    {
      "id": "p02",
      "name": "Jamal Musiala",
      "positionId": "pos-p02",
      "teamId": "ENG",
      "managerId": "p01",
      "successorForId": "p01",
      "disc": "CI",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p03",
      "name": "Florian Wirtz",
      "positionId": "pos-p03",
      "teamId": "ENG",
      "managerId": "p01",
      "successorForId": null,
      "disc": "CD",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p04",
      "name": "Phil Foden",
      "positionId": "pos-p04",
      "teamId": "ENG",
      "managerId": "p01",
      "successorForId": null,
      "disc": "SC",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p05",
      "name": "Kylian Mbappe",
      "positionId": "pos-p05",
      "teamId": "EXE",
      "managerId": null,
      "successorForId": null,
      "disc": "DI",
      "potential": "high",
      "photoUrl": null
    },
    {
      "id": "p06",
      "name": "Erling Haaland",
      "positionId": "pos-p06",
      "teamId": "EXE",
      "managerId": "p05",
      "successorForId": null,
      "disc": "DC",
      "potential": "high",
      "photoUrl": null
    },
    {
      "id": "p07",
      "name": "Rodri",
      "positionId": "pos-p07",
      "teamId": "EXE",
      "managerId": "p05",
      "successorForId": "p05",
      "disc": "CS",
      "potential": "high",
      "photoUrl": null
    },
    {
      "id": "p08",
      "name": "Virgil van Dijk",
      "positionId": "pos-p08",
      "teamId": "EXE",
      "managerId": "p05",
      "successorForId": null,
      "disc": "SD",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p09",
      "name": "Pedri",
      "positionId": "pos-p09",
      "teamId": "FIN",
      "managerId": "p05",
      "successorForId": null,
      "disc": "C",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p10",
      "name": "Federico Valverde",
      "positionId": "pos-p10",
      "teamId": "FIN",
      "managerId": "p09",
      "successorForId": null,
      "disc": "CDS",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p11",
      "name": "Enzo Fernandez",
      "positionId": "pos-p11",
      "teamId": "FIN",
      "managerId": "p09",
      "successorForId": null,
      "disc": "SI",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p12",
      "name": "Antoine Griezmann",
      "positionId": "pos-p12",
      "teamId": "FIN",
      "managerId": "p09",
      "successorForId": null,
      "disc": "IC",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p13",
      "name": "Christian Pulisic",
      "positionId": "pos-p13",
      "teamId": "HR",
      "managerId": "p05",
      "successorForId": null,
      "disc": "IS",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p14",
      "name": "Declan Rice",
      "positionId": "pos-p14",
      "teamId": "HR",
      "managerId": "p13",
      "successorForId": "p13",
      "disc": "D",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p15",
      "name": "Cody Gakpo",
      "positionId": "pos-p15",
      "teamId": "HR",
      "managerId": "p13",
      "successorForId": null,
      "disc": "SDI",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p16",
      "name": "Alphonso Davies",
      "positionId": "pos-p16",
      "teamId": "HR",
      "managerId": "p13",
      "successorForId": null,
      "disc": "S",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p17",
      "name": "Lautaro Martinez",
      "positionId": "pos-p17",
      "teamId": "OPS",
      "managerId": "p05",
      "successorForId": null,
      "disc": "DCS",
      "potential": "high",
      "photoUrl": null
    },
    {
      "id": "p18",
      "name": "Julian Alvarez",
      "positionId": "pos-p18",
      "teamId": "OPS",
      "managerId": "p17",
      "successorForId": null,
      "disc": "DS",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p19",
      "name": "Achraf Hakimi",
      "positionId": "pos-p19",
      "teamId": "OPS",
      "managerId": "p17",
      "successorForId": null,
      "disc": "ID",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p20",
      "name": "Son Heung-min",
      "positionId": "pos-p20",
      "teamId": "OPS",
      "managerId": "p17",
      "successorForId": null,
      "disc": "IS",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p21",
      "name": "Vinicius Junior",
      "positionId": "pos-p21",
      "teamId": "SNM",
      "managerId": "p05",
      "successorForId": null,
      "disc": "I",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p22",
      "name": "Rafael Leao",
      "positionId": "pos-p22",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "CIS",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p23",
      "name": "Bukayo Saka",
      "positionId": "pos-p23",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "DI",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p24",
      "name": "Nico Williams",
      "positionId": "pos-p24",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "SC",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p25",
      "name": "Lionel Messi",
      "positionId": "pos-p25",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "I",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p26",
      "name": "Cristiano Ronaldo",
      "positionId": "pos-p26",
      "teamId": "EXE",
      "managerId": "p05",
      "successorForId": null,
      "disc": "D",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p27",
      "name": "Neymar Jr",
      "positionId": "pos-p27",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "I",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p28",
      "name": "Kevin De Bruyne",
      "positionId": "pos-p28",
      "teamId": "ENG",
      "managerId": "p01",
      "successorForId": null,
      "disc": "C",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p29",
      "name": "Luka Modric",
      "positionId": "pos-p29",
      "teamId": "OPS",
      "managerId": "p17",
      "successorForId": null,
      "disc": "S",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p30",
      "name": "Mohamed Salah",
      "positionId": "pos-p30",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "D",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p31",
      "name": "Harry Kane",
      "positionId": "pos-p31",
      "teamId": "FIN",
      "managerId": "p09",
      "successorForId": null,
      "disc": "D",
      "potential": "low",
      "photoUrl": null
    },
    {
      "id": "p32",
      "name": "Robert Lewandowski",
      "positionId": "pos-p32",
      "teamId": "OPS",
      "managerId": "p17",
      "successorForId": null,
      "disc": "C",
      "potential": "medium",
      "photoUrl": null
    },
    {
      "id": "p33",
      "name": "Lamine Yamal",
      "positionId": "pos-p33",
      "teamId": "SNM",
      "managerId": "p21",
      "successorForId": null,
      "disc": "I",
      "potential": "low",
      "photoUrl": null
    }
  ],
  "scores": [
    {
      "participantId": "p01",
      "kind": "behavioral",
      "value": 88
    },
    {
      "participantId": "p01",
      "kind": "technical",
      "value": 90
    },
    {
      "participantId": "p01",
      "kind": "performance",
      "value": 90
    },
    {
      "participantId": "p01",
      "kind": "leadership",
      "value": 92
    },
    {
      "participantId": "p01",
      "kind": "competency",
      "value": 96
    },
    {
      "participantId": "p01",
      "kind": "prediction",
      "value": 95
    },
    {
      "participantId": "p01",
      "kind": "engagement",
      "value": 86
    },
    {
      "participantId": "p02",
      "kind": "behavioral",
      "value": null
    },
    {
      "participantId": "p02",
      "kind": "technical",
      "value": 91
    },
    {
      "participantId": "p02",
      "kind": "performance",
      "value": 88
    },
    {
      "participantId": "p02",
      "kind": "leadership",
      "value": 72
    },
    {
      "participantId": "p02",
      "kind": "competency",
      "value": 85
    },
    {
      "participantId": "p02",
      "kind": "prediction",
      "value": 58
    },
    {
      "participantId": "p02",
      "kind": "engagement",
      "value": 79
    },
    {
      "participantId": "p03",
      "kind": "behavioral",
      "value": 74
    },
    {
      "participantId": "p03",
      "kind": "technical",
      "value": 86
    },
    {
      "participantId": "p03",
      "kind": "performance",
      "value": 82
    },
    {
      "participantId": "p03",
      "kind": "leadership",
      "value": 60
    },
    {
      "participantId": "p03",
      "kind": "competency",
      "value": 79
    },
    {
      "participantId": "p03",
      "kind": "prediction",
      "value": 76
    },
    {
      "participantId": "p03",
      "kind": "engagement",
      "value": 71
    },
    {
      "participantId": "p04",
      "kind": "behavioral",
      "value": 80
    },
    {
      "participantId": "p04",
      "kind": "technical",
      "value": 84
    },
    {
      "participantId": "p04",
      "kind": "performance",
      "value": 78
    },
    {
      "participantId": "p04",
      "kind": "leadership",
      "value": 84
    },
    {
      "participantId": "p04",
      "kind": "competency",
      "value": 88
    },
    {
      "participantId": "p04",
      "kind": "prediction",
      "value": 75
    },
    {
      "participantId": "p04",
      "kind": "engagement",
      "value": 82
    },
    {
      "participantId": "p05",
      "kind": "behavioral",
      "value": 90
    },
    {
      "participantId": "p05",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p05",
      "kind": "performance",
      "value": 96
    },
    {
      "participantId": "p05",
      "kind": "leadership",
      "value": 95
    },
    {
      "participantId": "p05",
      "kind": "competency",
      "value": 98
    },
    {
      "participantId": "p05",
      "kind": "prediction",
      "value": 96
    },
    {
      "participantId": "p05",
      "kind": "engagement",
      "value": 92
    },
    {
      "participantId": "p06",
      "kind": "behavioral",
      "value": 82
    },
    {
      "participantId": "p06",
      "kind": "technical",
      "value": 78
    },
    {
      "participantId": "p06",
      "kind": "performance",
      "value": 92
    },
    {
      "participantId": "p06",
      "kind": "leadership",
      "value": 70
    },
    {
      "participantId": "p06",
      "kind": "competency",
      "value": 90
    },
    {
      "participantId": "p06",
      "kind": "prediction",
      "value": 88
    },
    {
      "participantId": "p06",
      "kind": "engagement",
      "value": 80
    },
    {
      "participantId": "p07",
      "kind": "behavioral",
      "value": 85
    },
    {
      "participantId": "p07",
      "kind": "technical",
      "value": 88
    },
    {
      "participantId": "p07",
      "kind": "performance",
      "value": 85
    },
    {
      "participantId": "p07",
      "kind": "leadership",
      "value": 88
    },
    {
      "participantId": "p07",
      "kind": "competency",
      "value": 94
    },
    {
      "participantId": "p07",
      "kind": "prediction",
      "value": 91
    },
    {
      "participantId": "p07",
      "kind": "engagement",
      "value": 86
    },
    {
      "participantId": "p08",
      "kind": "behavioral",
      "value": 77
    },
    {
      "participantId": "p08",
      "kind": "technical",
      "value": 80
    },
    {
      "participantId": "p08",
      "kind": "performance",
      "value": 80
    },
    {
      "participantId": "p08",
      "kind": "leadership",
      "value": 90
    },
    {
      "participantId": "p08",
      "kind": "competency",
      "value": 89
    },
    {
      "participantId": "p08",
      "kind": "prediction",
      "value": 88
    },
    {
      "participantId": "p08",
      "kind": "engagement",
      "value": 84
    },
    {
      "participantId": "p09",
      "kind": "behavioral",
      "value": 80
    },
    {
      "participantId": "p09",
      "kind": "technical",
      "value": 85
    },
    {
      "participantId": "p09",
      "kind": "performance",
      "value": 84
    },
    {
      "participantId": "p09",
      "kind": "leadership",
      "value": 66
    },
    {
      "participantId": "p09",
      "kind": "competency",
      "value": 80
    },
    {
      "participantId": "p09",
      "kind": "prediction",
      "value": 79
    },
    {
      "participantId": "p09",
      "kind": "engagement",
      "value": 77
    },
    {
      "participantId": "p10",
      "kind": "behavioral",
      "value": 88
    },
    {
      "participantId": "p10",
      "kind": "technical",
      "value": 92
    },
    {
      "participantId": "p10",
      "kind": "performance",
      "value": 76
    },
    {
      "participantId": "p10",
      "kind": "leadership",
      "value": 74
    },
    {
      "participantId": "p10",
      "kind": "competency",
      "value": 86
    },
    {
      "participantId": "p10",
      "kind": "prediction",
      "value": 84
    },
    {
      "participantId": "p10",
      "kind": "engagement",
      "value": 80
    },
    {
      "participantId": "p11",
      "kind": "behavioral",
      "value": 63
    },
    {
      "participantId": "p11",
      "kind": "technical",
      "value": 68
    },
    {
      "participantId": "p11",
      "kind": "performance",
      "value": 70
    },
    {
      "participantId": "p11",
      "kind": "leadership",
      "value": 58
    },
    {
      "participantId": "p11",
      "kind": "competency",
      "value": 66
    },
    {
      "participantId": "p11",
      "kind": "prediction",
      "value": 60
    },
    {
      "participantId": "p11",
      "kind": "engagement",
      "value": 63
    },
    {
      "participantId": "p12",
      "kind": "behavioral",
      "value": 84
    },
    {
      "participantId": "p12",
      "kind": "technical",
      "value": 90
    },
    {
      "participantId": "p12",
      "kind": "performance",
      "value": 88
    },
    {
      "participantId": "p12",
      "kind": "leadership",
      "value": 80
    },
    {
      "participantId": "p12",
      "kind": "competency",
      "value": 92
    },
    {
      "participantId": "p12",
      "kind": "prediction",
      "value": 90
    },
    {
      "participantId": "p12",
      "kind": "engagement",
      "value": 84
    },
    {
      "participantId": "p13",
      "kind": "behavioral",
      "value": 72
    },
    {
      "participantId": "p13",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p13",
      "kind": "performance",
      "value": 72
    },
    {
      "participantId": "p13",
      "kind": "leadership",
      "value": 68
    },
    {
      "participantId": "p13",
      "kind": "competency",
      "value": 74
    },
    {
      "participantId": "p13",
      "kind": "prediction",
      "value": 73
    },
    {
      "participantId": "p13",
      "kind": "engagement",
      "value": 79
    },
    {
      "participantId": "p14",
      "kind": "behavioral",
      "value": 82
    },
    {
      "participantId": "p14",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p14",
      "kind": "performance",
      "value": 82
    },
    {
      "participantId": "p14",
      "kind": "leadership",
      "value": 86
    },
    {
      "participantId": "p14",
      "kind": "competency",
      "value": 88
    },
    {
      "participantId": "p14",
      "kind": "prediction",
      "value": 90
    },
    {
      "participantId": "p14",
      "kind": "engagement",
      "value": 86
    },
    {
      "participantId": "p15",
      "kind": "behavioral",
      "value": 58
    },
    {
      "participantId": "p15",
      "kind": "technical",
      "value": 62
    },
    {
      "participantId": "p15",
      "kind": "performance",
      "value": 60
    },
    {
      "participantId": "p15",
      "kind": "leadership",
      "value": 62
    },
    {
      "participantId": "p15",
      "kind": "competency",
      "value": 64
    },
    {
      "participantId": "p15",
      "kind": "prediction",
      "value": 55
    },
    {
      "participantId": "p15",
      "kind": "engagement",
      "value": 60
    },
    {
      "participantId": "p16",
      "kind": "behavioral",
      "value": 66
    },
    {
      "participantId": "p16",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p16",
      "kind": "performance",
      "value": 66
    },
    {
      "participantId": "p16",
      "kind": "leadership",
      "value": 90
    },
    {
      "participantId": "p16",
      "kind": "competency",
      "value": 80
    },
    {
      "participantId": "p16",
      "kind": "prediction",
      "value": 80
    },
    {
      "participantId": "p16",
      "kind": "engagement",
      "value": 78
    },
    {
      "participantId": "p17",
      "kind": "behavioral",
      "value": 82
    },
    {
      "participantId": "p17",
      "kind": "technical",
      "value": 78
    },
    {
      "participantId": "p17",
      "kind": "performance",
      "value": 94
    },
    {
      "participantId": "p17",
      "kind": "leadership",
      "value": 84
    },
    {
      "participantId": "p17",
      "kind": "competency",
      "value": 93
    },
    {
      "participantId": "p17",
      "kind": "prediction",
      "value": 92
    },
    {
      "participantId": "p17",
      "kind": "engagement",
      "value": 86
    },
    {
      "participantId": "p18",
      "kind": "behavioral",
      "value": 74
    },
    {
      "participantId": "p18",
      "kind": "technical",
      "value": 72
    },
    {
      "participantId": "p18",
      "kind": "performance",
      "value": 80
    },
    {
      "participantId": "p18",
      "kind": "leadership",
      "value": 64
    },
    {
      "participantId": "p18",
      "kind": "competency",
      "value": 79
    },
    {
      "participantId": "p18",
      "kind": "prediction",
      "value": 76
    },
    {
      "participantId": "p18",
      "kind": "engagement",
      "value": 74
    },
    {
      "participantId": "p19",
      "kind": "behavioral",
      "value": 71
    },
    {
      "participantId": "p19",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p19",
      "kind": "performance",
      "value": 74
    },
    {
      "participantId": "p19",
      "kind": "leadership",
      "value": 78
    },
    {
      "participantId": "p19",
      "kind": "competency",
      "value": 83
    },
    {
      "participantId": "p19",
      "kind": "prediction",
      "value": 80
    },
    {
      "participantId": "p19",
      "kind": "engagement",
      "value": 73
    },
    {
      "participantId": "p20",
      "kind": "behavioral",
      "value": 68
    },
    {
      "participantId": "p20",
      "kind": "technical",
      "value": 70
    },
    {
      "participantId": "p20",
      "kind": "performance",
      "value": 86
    },
    {
      "participantId": "p20",
      "kind": "leadership",
      "value": 58
    },
    {
      "participantId": "p20",
      "kind": "competency",
      "value": 76
    },
    {
      "participantId": "p20",
      "kind": "prediction",
      "value": 74
    },
    {
      "participantId": "p20",
      "kind": "engagement",
      "value": 72
    },
    {
      "participantId": "p21",
      "kind": "behavioral",
      "value": 86
    },
    {
      "participantId": "p21",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p21",
      "kind": "performance",
      "value": 91
    },
    {
      "participantId": "p21",
      "kind": "leadership",
      "value": 82
    },
    {
      "participantId": "p21",
      "kind": "competency",
      "value": 94
    },
    {
      "participantId": "p21",
      "kind": "prediction",
      "value": 92
    },
    {
      "participantId": "p21",
      "kind": "engagement",
      "value": 88
    },
    {
      "participantId": "p22",
      "kind": "behavioral",
      "value": 60
    },
    {
      "participantId": "p22",
      "kind": "technical",
      "value": 64
    },
    {
      "participantId": "p22",
      "kind": "performance",
      "value": 68
    },
    {
      "participantId": "p22",
      "kind": "leadership",
      "value": 55
    },
    {
      "participantId": "p22",
      "kind": "competency",
      "value": 62
    },
    {
      "participantId": "p22",
      "kind": "prediction",
      "value": 52
    },
    {
      "participantId": "p22",
      "kind": "engagement",
      "value": 60
    },
    {
      "participantId": "p23",
      "kind": "behavioral",
      "value": 84
    },
    {
      "participantId": "p23",
      "kind": "technical",
      "value": null
    },
    {
      "participantId": "p23",
      "kind": "performance",
      "value": 84
    },
    {
      "participantId": "p23",
      "kind": "leadership",
      "value": 88
    },
    {
      "participantId": "p23",
      "kind": "competency",
      "value": 90
    },
    {
      "participantId": "p23",
      "kind": "prediction",
      "value": 90
    },
    {
      "participantId": "p23",
      "kind": "engagement",
      "value": 85
    },
    {
      "participantId": "p24",
      "kind": "behavioral",
      "value": 58
    },
    {
      "participantId": "p24",
      "kind": "technical",
      "value": 70
    },
    {
      "participantId": "p24",
      "kind": "performance",
      "value": 58
    },
    {
      "participantId": "p24",
      "kind": "leadership",
      "value": 70
    },
    {
      "participantId": "p24",
      "kind": "competency",
      "value": 72
    },
    {
      "participantId": "p24",
      "kind": "prediction",
      "value": 68
    },
    {
      "participantId": "p24",
      "kind": "engagement",
      "value": 74
    },
    {
      "participantId": "p25",
      "kind": "behavioral",
      "value": 90
    },
    {
      "participantId": "p25",
      "kind": "technical",
      "value": 82
    },
    {
      "participantId": "p25",
      "kind": "performance",
      "value": 95
    },
    {
      "participantId": "p25",
      "kind": "leadership",
      "value": 88
    },
    {
      "participantId": "p25",
      "kind": "competency",
      "value": 94
    },
    {
      "participantId": "p25",
      "kind": "prediction",
      "value": 93
    },
    {
      "participantId": "p25",
      "kind": "engagement",
      "value": 92
    },
    {
      "participantId": "p26",
      "kind": "behavioral",
      "value": 88
    },
    {
      "participantId": "p26",
      "kind": "technical",
      "value": 80
    },
    {
      "participantId": "p26",
      "kind": "performance",
      "value": 96
    },
    {
      "participantId": "p26",
      "kind": "leadership",
      "value": 92
    },
    {
      "participantId": "p26",
      "kind": "competency",
      "value": 95
    },
    {
      "participantId": "p26",
      "kind": "prediction",
      "value": 95
    },
    {
      "participantId": "p26",
      "kind": "engagement",
      "value": 90
    },
    {
      "participantId": "p27",
      "kind": "behavioral",
      "value": 84
    },
    {
      "participantId": "p27",
      "kind": "technical",
      "value": 78
    },
    {
      "participantId": "p27",
      "kind": "performance",
      "value": 86
    },
    {
      "participantId": "p27",
      "kind": "leadership",
      "value": 80
    },
    {
      "participantId": "p27",
      "kind": "competency",
      "value": 85
    },
    {
      "participantId": "p27",
      "kind": "prediction",
      "value": 82
    },
    {
      "participantId": "p27",
      "kind": "engagement",
      "value": 84
    },
    {
      "participantId": "p28",
      "kind": "behavioral",
      "value": 86
    },
    {
      "participantId": "p28",
      "kind": "technical",
      "value": 94
    },
    {
      "participantId": "p28",
      "kind": "performance",
      "value": 92
    },
    {
      "participantId": "p28",
      "kind": "leadership",
      "value": 84
    },
    {
      "participantId": "p28",
      "kind": "competency",
      "value": 93
    },
    {
      "participantId": "p28",
      "kind": "prediction",
      "value": 63
    },
    {
      "participantId": "p28",
      "kind": "engagement",
      "value": 88
    },
    {
      "participantId": "p29",
      "kind": "behavioral",
      "value": 88
    },
    {
      "participantId": "p29",
      "kind": "technical",
      "value": 85
    },
    {
      "participantId": "p29",
      "kind": "performance",
      "value": 90
    },
    {
      "participantId": "p29",
      "kind": "leadership",
      "value": 86
    },
    {
      "participantId": "p29",
      "kind": "competency",
      "value": 91
    },
    {
      "participantId": "p29",
      "kind": "prediction",
      "value": 90
    },
    {
      "participantId": "p29",
      "kind": "engagement",
      "value": 89
    },
    {
      "participantId": "p30",
      "kind": "behavioral",
      "value": 85
    },
    {
      "participantId": "p30",
      "kind": "technical",
      "value": 80
    },
    {
      "participantId": "p30",
      "kind": "performance",
      "value": 93
    },
    {
      "participantId": "p30",
      "kind": "leadership",
      "value": 82
    },
    {
      "participantId": "p30",
      "kind": "competency",
      "value": 90
    },
    {
      "participantId": "p30",
      "kind": "prediction",
      "value": 89
    },
    {
      "participantId": "p30",
      "kind": "engagement",
      "value": 90
    },
    {
      "participantId": "p31",
      "kind": "behavioral",
      "value": 84
    },
    {
      "participantId": "p31",
      "kind": "technical",
      "value": 86
    },
    {
      "participantId": "p31",
      "kind": "performance",
      "value": 91
    },
    {
      "participantId": "p31",
      "kind": "leadership",
      "value": 85
    },
    {
      "participantId": "p31",
      "kind": "competency",
      "value": 90
    },
    {
      "participantId": "p31",
      "kind": "prediction",
      "value": 88
    },
    {
      "participantId": "p31",
      "kind": "engagement",
      "value": 87
    },
    {
      "participantId": "p32",
      "kind": "behavioral",
      "value": 82
    },
    {
      "participantId": "p32",
      "kind": "technical",
      "value": 84
    },
    {
      "participantId": "p32",
      "kind": "performance",
      "value": 88
    },
    {
      "participantId": "p32",
      "kind": "leadership",
      "value": 80
    },
    {
      "participantId": "p32",
      "kind": "competency",
      "value": 86
    },
    {
      "participantId": "p32",
      "kind": "prediction",
      "value": 84
    },
    {
      "participantId": "p32",
      "kind": "engagement",
      "value": 83
    },
    {
      "participantId": "p33",
      "kind": "behavioral",
      "value": 86
    },
    {
      "participantId": "p33",
      "kind": "technical",
      "value": 80
    },
    {
      "participantId": "p33",
      "kind": "performance",
      "value": 88
    },
    {
      "participantId": "p33",
      "kind": "leadership",
      "value": 80
    },
    {
      "participantId": "p33",
      "kind": "competency",
      "value": 89
    },
    {
      "participantId": "p33",
      "kind": "prediction",
      "value": 87
    },
    {
      "participantId": "p33",
      "kind": "engagement",
      "value": 88
    }
  ],
  "assignments": [
    {
      "id": "a01",
      "participantId": "p01",
      "type": "Leadership Assessment",
      "status": "completed",
      "dueDate": "2026-05-10"
    },
    {
      "id": "a02",
      "participantId": "p02",
      "type": "Technical Review",
      "status": "in_progress",
      "dueDate": "2026-06-01"
    },
    {
      "id": "a03",
      "participantId": "p03",
      "type": "IDP Check-in",
      "status": "todo",
      "dueDate": "2026-06-15"
    },
    {
      "id": "a04",
      "participantId": "p04",
      "type": "360 Feedback",
      "status": "waiting_review",
      "dueDate": "2026-05-28"
    },
    {
      "id": "a05",
      "participantId": "p05",
      "type": "Succession Review",
      "status": "completed",
      "dueDate": "2026-04-30"
    },
    {
      "id": "a06",
      "participantId": "p06",
      "type": "Leadership Assessment",
      "status": "in_progress",
      "dueDate": "2026-06-05"
    },
    {
      "id": "a07",
      "participantId": "p07",
      "type": "Competency Test",
      "status": "completed",
      "dueDate": "2026-05-12"
    },
    {
      "id": "a08",
      "participantId": "p09",
      "type": "IDP Check-in",
      "status": "todo",
      "dueDate": "2026-06-20"
    },
    {
      "id": "a09",
      "participantId": "p10",
      "type": "Technical Review",
      "status": "in_progress",
      "dueDate": "2026-06-02"
    },
    {
      "id": "a10",
      "participantId": "p12",
      "type": "360 Feedback",
      "status": "completed",
      "dueDate": "2026-05-18"
    },
    {
      "id": "a11",
      "participantId": "p13",
      "type": "Engagement Survey",
      "status": "waiting_review",
      "dueDate": "2026-05-25"
    },
    {
      "id": "a12",
      "participantId": "p14",
      "type": "Leadership Assessment",
      "status": "in_progress",
      "dueDate": "2026-06-08"
    },
    {
      "id": "a13",
      "participantId": "p17",
      "type": "Succession Review",
      "status": "completed",
      "dueDate": "2026-05-05"
    },
    {
      "id": "a14",
      "participantId": "p18",
      "type": "IDP Check-in",
      "status": "todo",
      "dueDate": "2026-06-22"
    },
    {
      "id": "a15",
      "participantId": "p20",
      "type": "Competency Test",
      "status": "waiting_review",
      "dueDate": "2026-05-30"
    },
    {
      "id": "a16",
      "participantId": "p21",
      "type": "Leadership Assessment",
      "status": "completed",
      "dueDate": "2026-05-14"
    },
    {
      "id": "a17",
      "participantId": "p23",
      "type": "360 Feedback",
      "status": "in_progress",
      "dueDate": "2026-06-10"
    },
    {
      "id": "a18",
      "participantId": "p11",
      "type": "IDP Check-in",
      "status": "todo",
      "dueDate": "2026-06-25"
    }
  ]
};
