// PGS-1134 / E2 seed codegen: participants.csv + assignments.csv → src/data/model/generated.ts
// Run: npm run seed   (also validates referential integrity — fails loud on orphan refs)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(ROOT, p), "utf8").replace(/^﻿/, "");

function parseCSV(text) {
  const lines = text.split(/\r?\n/).filter((l) => l.trim());
  const headers = lines[0].split(",").map((h) => h.trim());
  return lines.slice(1).map((line) => {
    const vals = line.split(",");
    return headers.reduce((o, h, i) => ((o[h] = (vals[i] ?? "").trim()), o), {});
  });
}

const num = (v) => (v === "" || v == null ? null : Number(v));

const TEAMS = {
  ENG: { name: "Engineering Team", type: "FUNCTIONAL", leaderId: "p01", reportToId: "p05" },
  EXE: { name: "Executive Office Team", type: "FUNCTIONAL", leaderId: "p05", reportToId: null },
  FIN: { name: "Finance Team", type: "FUNCTIONAL", leaderId: "p09", reportToId: "p05" },
  HR: { name: "Human Resources Team", type: "FUNCTIONAL", leaderId: "p13", reportToId: "p05" },
  OPS: { name: "Operations Team", type: "STRUCTURAL", leaderId: "p17", reportToId: "p05" },
  SNM: { name: "Sales & Marketing Team", type: "FUNCTIONAL", leaderId: "p21", reportToId: "p05" },
};

const SCORE_KINDS = ["behavioral", "technical", "performance", "leadership", "competency", "prediction", "engagement"];

const pRows = parseCSV(read("public/data/participants.csv"));
const aRows = parseCSV(read("public/data/assignments.csv"));

const positions = pRows.map((r) => ({ id: `pos-${r.id}`, title: r.position, department: r.department }));
const teams = Object.entries(TEAMS).map(([id, t]) => ({ id, ...t }));
const participants = pRows.map((r) => ({
  id: r.id,
  name: r.name,
  positionId: `pos-${r.id}`,
  teamId: r.team || null,
  managerId: r.manager_id || null,
  successorForId: r.successor_for || null,
  disc: r.disc,
  potential: r.potential,
  photoUrl: r.photo_url || null,
}));
const scores = pRows.flatMap((r) => SCORE_KINDS.map((kind) => ({ participantId: r.id, kind, value: num(r[kind === "leadership" ? "leadership" : kind]) })));
const assignments = aRows.map((r) => ({ id: r.id, participantId: r.participant_id, type: r.type, status: r.status, dueDate: r.due_date || null }));

// --- Referential integrity (AC-5874): fail loud on orphan refs ---
const pIds = new Set(participants.map((p) => p.id));
const tIds = new Set(teams.map((t) => t.id));
const errors = [];
for (const p of participants) {
  if (p.teamId && !tIds.has(p.teamId)) errors.push(`participant ${p.id}: unknown teamId ${p.teamId}`);
  if (p.managerId && !pIds.has(p.managerId)) errors.push(`participant ${p.id}: unknown managerId ${p.managerId}`);
  if (p.successorForId && !pIds.has(p.successorForId)) errors.push(`participant ${p.id}: unknown successorForId ${p.successorForId}`);
}
for (const t of teams) {
  if (t.leaderId && !pIds.has(t.leaderId)) errors.push(`team ${t.id}: unknown leaderId ${t.leaderId}`);
  if (t.reportToId && !pIds.has(t.reportToId)) errors.push(`team ${t.id}: unknown reportToId ${t.reportToId}`);
}
for (const a of assignments) {
  if (!pIds.has(a.participantId)) errors.push(`assignment ${a.id}: unknown participantId ${a.participantId}`);
}
if (errors.length) {
  console.error("Seed referential-integrity FAILED:\n  " + errors.join("\n  "));
  process.exit(1);
}

const data = { positions, teams, participants, scores, assignments };
const out =
  `// AUTO-GENERATED by scripts/seed.mjs — do not edit by hand.\n` +
  `// Source of record: public/data/participants.csv + assignments.csv. Regenerate: npm run seed\n` +
  `import type { CanonicalData } from "./types";\n\n` +
  `export const CANONICAL: CanonicalData = ${JSON.stringify(data, null, 2)};\n`;
writeFileSync(join(ROOT, "src/data/model/generated.ts"), out);

console.log(`seed ok: ${participants.length} participants, ${teams.length} teams, ${scores.length} scores, ${assignments.length} assignments`);
